server:
  port: 8080

spring:
  application:
    name: costco-saas-api
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5433/costco_saas}
    username: ${SPRING_DATASOURCE_USERNAME:costco_admin}
    password: ${SPRING_DATASOURCE_PASSWORD:costco_password}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: false
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
  jackson:
    serialization:
      write-dates-as-timestamps: false

# JWT Configuration
jwt:
  secret: ${JWT_SECRET:dGhpc0lzQVZlcnlMb25nU2VjcmV0S2V5Rm9yQ29zdGNvTWluaW5nU2Fhc1BsYXRmb3JtSldUVG9rZW5z}
  access-token-expiration-ms: ${JWT_EXPIRATION_MS:86400000}
  refresh-token-expiration-ms: 604800000

# AWS Configuration
aws:
  region: ${AWS_REGION:ap-south-1}
  sqs:
    queue-url: ${AWS_SQS_QUEUE_URL:https://sqs.ap-south-1.amazonaws.com/824309437901/costco-telemetry-queue}
    poll-interval-ms: 5000
    endpoint: ${AWS_SQS_ENDPOINT:}
  s3:
    reports-bucket: ${AWS_S3_REPORTS_BUCKET:costco-saas-reports}

# Actuator
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: when-authorized

logging:
  level:
    za.co.costcomining: INFO
    org.springframework.security: WARN
